# Generated by Django 5.2.1 on 2025-05-17 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_vuelo', models.DateTimeField()),
                ('fecha_emision', models.DateField()),
                ('fecha_deposito', models.DateField()),
                ('fecha_pago_total', models.DateField()),
                ('compania', models.CharField(max_length=100)),
                ('localizador', models.CharField(blank=True, max_length=20, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('deposito_realizado', models.BooleanField(default=False)),
                ('emitida', models.BooleanField(default=False)),
                ('pagado_total', models.BooleanField(default=False)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_vuelo'],
            },
        ),
    ]
