# Generated by Django 5.2.1 on 2025-05-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_vuelo',
            field=models.DateField(),
        ),
    ]
