# Generated by Django 5.2.1 on 2025-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_email_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_cancelacion_plazas',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cancelación Plazas'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_cancelacion_total',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cancelación Total'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_nombres',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nombres'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('MD', 'Metálico/Datafono'), ('TRANSF', 'Transferencia')], max_length=10, null=True, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='importe_deposito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importe Depósito'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='importe_pago_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importe Pago Total'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_agencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Agencia'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observaciones_cancelacion_plazas',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Cancelación Plazas'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_cliente',
            field=models.CharField(choices=[('AD_HOC', 'Ad Hoc'), ('CATALOGO', 'Catálogo'), ('PLAZA_A_PLAZA', 'Plaza a Plaza')], default=1, max_length=20, verbose_name='Tipo de Cliente'),
            preserve_default=False,
        ),
    ]
